version: '3'

services:
  app:
    image: angdesarrollo/bun-boilerplate
    restart: always
    build:
      context: .
      target: ${STAGE}
    container_name: bun_app
    ports:
      - ${PORT}:${PORT}
    environment:
      STAGE: ${STAGE}
      PORT: ${PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_URL: ${MONGO_URL}
      BUN_APP_NAME: ${BUN_APP_NAME}
      TOKEN_EXPIRES_IN: ${TOKEN_EXPIRES_IN},
      COOKIE_EXPIRES_IN: ${COOKIE_EXPIRES_IN},
      TOKEN_SECRET: ${TOKEN_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
